CANCEL_TEXT = '`--CANCELED--`'
ADMIN_PANEL_TEXT = '`--ADMIN--`'
SUCCESS = '`--SUCCESS--`'

# Vk console
VK_CONSOLE_TEXT = '`--VK CONSOLE--`'
# parsing
GET_GROUP_TEXT = '`--GET LINK ON A GROUP--`'
CLOSED_GROUP_TEXT = '`--CLOSED GROUP--`'
GET_COUNT_OF_POSTS_TEXT = '`--GET COUNT OF POSTS--`'
INCORRECT_GROUP_TEXT = '`--INCORRECT GROUP LINK--`'
INCORRECT_COUNT_OF_POSTS = '`--COUNT OF POST MUST BE INTEGER--`'
PARSING_PROCESS = '`--PARSING RUNNING--`'

ADD_GROUP_GET_GROUP_LINK = '`--GET GROUP LINK--`'
ADD_GROUP_LINK_WITH_CHANNEL = '`--LINK THIS GROUP WITH CHANNEL?--`'

LINK_GROUP_WITH_CHANNEL = '`--SELECT CHANNEL--`'
