START_TEXT = 'Hi. How i can help you?'

PARSING = 'PARSING'
GET_GROUP_ID_TEXT = 'Type group id'
INCORRECT_GROUP_ID_TEXT = 'sems that domain of group is incorrect'
CLOSED_GROUP_TEXT = 'Looks like the group is closed. I can\'t get posts from these groups.\nChoose another group'
GET_COUNT_OF_POSTS_TEXT = 'Alright! Now get me count of posts'
READY_TO_PARSE_TEXT = 'Good. If you ready press button PARS on the keyboard'
PARSING_PROCESS = 'parsing in progress'
INCORRECT_COUNT_OF_POSTS = 'Count of post should be digits!'
